# fly.toml app configuration file for peppertools

app = "peppertools"
primary_region = "gru"
console_command = "/code/manage.py shell"

[build.args]
  BP_CPYTHON_VERSION = "3.12.2"

[build]
  builtin = "python"

[build.settings]
  pythonbase = "3.12-bullseye"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
