# Generated by Django 3.1 on 2021-05-22 02:54

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models
import pepperadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', localflavor.br.models.BRCNPJField(blank=True, db_column='cnpj', max_length=18, null=True)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=254, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True)),
                ('telefone', models.IntegerField(blank=True, db_column='telefone', null=True)),
                ('celular', models.IntegerField(blank=True, db_column='celular', null=True)),
                ('cod_cli', models.CharField(blank=True, db_column='cod_cli', default='', max_length=10, null=True)),
                ('fax', models.CharField(blank=True, db_column='fax', max_length=50, null=True)),
                ('ie', models.IntegerField(blank=True, db_column='ie', null=True)),
                ('cep', localflavor.br.models.BRPostalCodeField(blank=True, db_column='cep', max_length=9, null=True)),
                ('cidade', models.CharField(db_column='cidade', default=None, max_length=120)),
                ('estado', localflavor.br.models.BRStateField(blank=True, db_column='estado', default=None, max_length=2, null=True)),
                ('endereco', models.CharField(blank=True, db_column='endereco', max_length=254, null=True)),
                ('obs', models.CharField(blank=True, db_column='obs', default='', max_length=254, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', max_length=254)),
                ('mm', models.IntegerField(db_column='mm')),
            ],
            options={
                'db_table': 'Ferramenta',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=254)),
                ('descricao', models.TextField(db_column='descricao')),
            ],
            options={
                'db_table': 'itens',
            },
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('nome', models.CharField(db_column='nome', max_length=254)),
                ('numero_inicial', models.IntegerField(db_column='numero_inicial', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'linha',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=254, null=True)),
                ('custo', models.IntegerField(blank=True, db_column='custo', default=None, null=True)),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254)),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'Tipo',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('numero', models.AutoField(db_column='numero', primary_key=True, serialize=False)),
                ('ano', models.IntegerField(db_column='ano', validators=[django.core.validators.MinValueValidator(1984), pepperadmin.models.max_value_current_year], verbose_name='year')),
                ('data', models.DateTimeField(db_column='data', default=datetime.datetime.now)),
                ('prazo_entrega', models.DateTimeField(blank=True, db_column='prazo_entrega')),
                ('prazo_pagamento', models.DateTimeField(blank=True, db_column='prazo_pagto')),
                ('ipi', models.CharField(db_column='ipi', max_length=50)),
                ('icms', models.CharField(db_column='icms', max_length=50)),
                ('cliente', models.ForeignKey(db_column='id_cliente', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_orcamento', to='pepperadmin.cliente')),
                ('item', models.ManyToManyField(blank=True, db_column='cod_item', related_name='item_orcamento', to='pepperadmin.Item')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'db_table': 'orcamento',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='material_item',
            field=models.ForeignKey(blank=True, db_column='cod_mat', on_delete=django.db.models.deletion.CASCADE, related_name='materialitem', to='pepperadmin.material'),
        ),
        migrations.CreateModel(
            name='Cadastro_OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.TextField(blank=True, choices=[('fabricação', 'fabricação'), ('afiação', 'afiação')], db_column='Tipo', default='fabricação', null=True)),
                ('Numero_Os', models.IntegerField(db_column='Numero_Os', default=pepperadmin.models.get_last_os)),
                ('Data', models.DateTimeField(blank=True, db_column='Data', max_length=50, null=True)),
                ('Prazo', models.DateTimeField(blank=True, db_column='Prazo', max_length=50, null=True)),
                ('gravacao', models.CharField(blank=True, db_column='gravacao', max_length=50, null=True)),
                ('gravacao2', models.CharField(blank=True, db_column='gravacao2', max_length=50, null=True)),
                ('Ferramenta', models.TextField(blank=True, db_column='Ferramenta', null=True)),
                ('Material', models.CharField(blank=True, db_column='Material', default='HSS', max_length=50, null=True)),
                ('Especificacao', models.TextField(blank=True, db_column='Especificacao', null=True)),
                ('Quantidade', models.IntegerField(blank=True, db_column='Quantidade', null=True)),
                ('unidade', models.CharField(blank=True, choices=[('peca', 'Peça'), ('jogo', 'Jogo')], db_column='unidade', default='peca', max_length=50, null=True)),
                ('Desenho_Cliente', models.CharField(blank=True, db_column='Desenho_Cliente', max_length=50, null=True)),
                ('Desenho_Pimentel', models.CharField(blank=True, db_column='Desenho_Pimentel', max_length=50, null=True)),
                ('Numero_Nf', models.IntegerField(blank=True, db_column='Numero_Nf', null=True)),
                ('Numero_Pedido', models.IntegerField(blank=True, db_column='Numero_Pedido', null=True)),
                ('Data_Nf', models.DateTimeField(blank=True, db_column='Data_Nf', null=True)),
                ('Data_Pedido', models.DateTimeField(blank=True, db_column='Data_Pedido', null=True)),
                ('STATUS', models.CharField(blank=True, db_column='STATUS', max_length=70, null=True)),
                ('Cliente', models.ForeignKey(db_column='Id_Cliente', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_os', to='pepperadmin.cliente')),
                ('Linha', models.ForeignKey(blank=True, db_column='id_Linha', default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linha_os', to='pepperadmin.linha')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'db_table': 'cadastro_os',
            },
        ),
    ]
