# Generated by Django 3.1 on 2021-05-23 20:40

import django.core.validators
from django.db import migrations, models
import pepperadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='ano',
            field=models.IntegerField(db_column='ano', default=pepperadmin.models.max_value_current_year, validators=[django.core.validators.MinValueValidator(1984), pepperadmin.models.max_value_current_year], verbose_name='ano'),
        ),
    ]
