# Generated by Django 3.1 on 2021-05-23 20:43

import django.core.validators
from django.db import migrations, models
import pepperadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0002_auto_20210523_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='ano',
            field=models.IntegerField(db_column='ano', default=2021, validators=[django.core.validators.MinValueValidator(1984), pepperadmin.models.max_value_current_year], verbose_name='ano'),
        ),
    ]
