# Generated by Django 3.1 on 2021-05-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0003_auto_20210523_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='material_item',
            new_name='material',
        ),
    ]
