# Generated by Django 3.1 on 2021-05-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0004_auto_20210523_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_os',
            name='Tipo',
            field=models.TextField(blank=True, choices=[('fabricacao', 'fabricação'), ('afiacao', 'afiação')], db_column='Tipo', default='fabricacao', null=True),
        ),
    ]
