# Generated by Django 3.1 on 2021-05-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0005_auto_20210523_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_os',
            name='Tipo',
            field=models.TextField(blank=True, choices=[('afiacao', 'afiação'), ('fabricacao', 'fabricação'), ('modificacao', 'modificação')], db_column='Tipo', default='afiacao', null=True),
        ),
    ]
