# Generated by Django 3.1 on 2021-05-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0008_auto_20210523_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Materiai'},
        ),
    ]
