# Generated by Django 3.2.3 on 2021-05-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0009_auto_20210523_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
    ]
