# Generated by Django 3.2.3 on 2021-05-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0010_alter_material_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Materiais'},
        ),
    ]
