# Generated by Django 3.2.3 on 2021-05-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0011_alter_material_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Itens'},
        ),
    ]
