# Generated by Django 3.2.3 on 2021-05-24 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0012_alter_item_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, db_column='Nome', max_length=254, null=True)),
                ('Tempo_Objetivo', models.TimeField(blank=True, db_column='Tempo_Objetivo', null=True)),
            ],
            options={
                'db_table': 'processos',
            },
        ),
        migrations.AlterField(
            model_name='cadastro_os',
            name='Data',
            field=models.DateTimeField(blank=True, db_column='Data', default=django.utils.timezone.now, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='data',
            field=models.DateTimeField(db_column='data', default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Historico_Os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField(blank=True, db_column='inicio', null=True, verbose_name='Início')),
                ('fim', models.TimeField(blank=True, db_column='fim', null=True, verbose_name='Fim')),
                ('ocorrencias', models.TextField(blank=True, db_column='ocorrencias', null=True)),
                ('periodo', models.IntegerField(blank=True, db_column='periodo', null=True)),
                ('data', models.DateTimeField(blank=True, db_column='data', default=django.utils.timezone.now, null=True)),
                ('qtd', models.IntegerField(blank=True, db_column='qtd', null=True)),
                ('os', models.ForeignKey(blank=True, db_column='id_os', null=True, on_delete=django.db.models.deletion.CASCADE, to='pepperadmin.cadastro_os', verbose_name='Ordem de Serviço')),
                ('processo', models.ForeignKey(blank=True, db_column='id_proc', null=True, on_delete=django.db.models.deletion.CASCADE, to='pepperadmin.processos', verbose_name='Processo')),
            ],
            options={
                'db_table': 'Historico_os',
            },
        ),
    ]
