# Generated by Django 3.2.3 on 2021-05-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0013_auto_20210524_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='custo',
            field=models.IntegerField(blank=True, db_column='custo', null=True),
        ),
    ]
