# Generated by Django 3.2.3 on 2021-05-26 20:40

from django.db import migrations, models
import pepperadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0016_alter_historico_os_os'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico_os',
            options={'verbose_name': 'Localização O.S', 'verbose_name_plural': 'Localizar O.S'},
        ),
        migrations.AlterField(
            model_name='cadastro_os',
            name='Numero_Os',
            field=models.IntegerField(db_column='Numero_Os', default=pepperadmin.models.get_last_os, editable=False),
        ),
    ]
