# Generated by Django 3.2.3 on 2021-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0018_auto_20210527_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ie',
            field=models.CharField(blank=True, db_column='ie', max_length=254, null=True),
        ),
    ]
