# Generated by Django 3.2.3 on 2021-05-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0019_alter_cliente_ie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cod_cli',
            field=models.CharField(blank=True, db_column='cod_cli', default='', max_length=50, null=True),
        ),
    ]
