# Generated by Django 3.2.3 on 2021-05-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0020_alter_cliente_cod_cli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, db_column='endereco', max_length=512, null=True),
        ),
    ]
