# Generated by Django 3.2.3 on 2021-05-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0024_alter_cliente_cidade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Processos',
            new_name='Processo',
        ),
        migrations.RemoveField(
            model_name='cadastro_os',
            name='Material',
        ),
        migrations.AddField(
            model_name='cadastro_os',
            name='Material',
            field=models.ManyToManyField(blank=True, db_column='Material', max_length=50, null=True, to='pepperadmin.Material'),
        ),
    ]
