# Generated by Django 3.2.3 on 2021-05-28 22:38

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0025_auto_20210528_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', localflavor.br.models.BRCNPJField(blank=True, db_column='cnpj', max_length=18, null=True)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=500, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, db_column='telefone', max_length=254, null=True)),
                ('celular', models.CharField(blank=True, db_column='celular', max_length=254, null=True)),
                ('cod_forn', models.CharField(blank=True, db_column='cod_cli', default='', max_length=50, null=True)),
                ('fax', models.CharField(blank=True, db_column='fax', max_length=50, null=True)),
                ('ie', models.CharField(blank=True, db_column='ie', max_length=254, null=True)),
                ('cep', localflavor.br.models.BRPostalCodeField(blank=True, db_column='cep', max_length=9, null=True)),
                ('cidade', models.CharField(blank=True, db_column='cidade', max_length=120, null=True)),
                ('estado', localflavor.br.models.BRStateField(blank=True, db_column='estado', default=None, max_length=2, null=True)),
                ('endereco', models.TextField(blank=True, db_column='endereco', null=True)),
                ('obs', models.CharField(blank=True, db_column='obs', default='', max_length=254, null=True)),
            ],
            options={
                'db_table': 'Fornecedor',
            },
        ),
        migrations.RemoveField(
            model_name='cadastro_os',
            name='Material',
        ),
        migrations.AddField(
            model_name='cadastro_os',
            name='Material',
            field=models.ForeignKey(blank=True, db_column='Material', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='pepperadmin.material'),
        ),
    ]
