# Generated by Django 3.2.3 on 2021-05-29 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0026_auto_20210528_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_os',
            name='Data',
            field=models.DateField(blank=True, db_column='Data', default=django.utils.timezone.now, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_os',
            name='Data_Nf',
            field=models.DateField(blank=True, db_column='Data_Nf', null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_os',
            name='Data_Pedido',
            field=models.DateField(blank=True, db_column='Data_Pedido', null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_os',
            name='Prazo',
            field=models.DateField(blank=True, db_column='Prazo', max_length=50, null=True),
        ),
    ]
