# Generated by Django 3.2.3 on 2021-05-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0027_auto_20210529_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_os',
            name='unidade',
            field=models.CharField(blank=True, choices=[('Peça', 'Peça'), ('Jogo', 'Jogo')], db_column='unidade', default='peca', max_length=50, null=True),
        ),
    ]
