# Generated by Django 3.2.3 on 2021-05-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0028_alter_cadastro_os_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_os',
            name='Material',
            field=models.CharField(blank=True, db_column='Material', max_length=50, null=True),
        ),
    ]
