# Generated by Django 3.2.3 on 2021-06-02 13:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pepperadmin.models
from pepperadmin.admin import PedidoModel


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0029_alter_cadastro_os_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='Nome',
        ),
        migrations.AddField(
            model_name='item',
            name='preco',
            field=models.FloatField(blank=True, db_column='preco', null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='processo',
            name='procname',
            field=models.CharField(blank=True, db_column='Nome', max_length=254, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cadastro_os',
            name='Data',
            field=models.DateField(blank=True, db_column='Data', default='02/06/2021', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='10:26:12', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='processo',
            field=models.ForeignKey(blank=True, db_column='id_proc', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_proc', to='pepperadmin.processo', verbose_name='Processo'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.ManyToManyField(blank=True, db_column='cod_mat', related_name='materialitem', to='pepperadmin.Material'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.IntegerField(db_column='numero', default=pepperadmin.models.Pedido.get_last_pedido, editable=False)),
                ('ano', models.IntegerField(db_column='ano', default=2021, validators=[django.core.validators.MinValueValidator(1984), pepperadmin.models.max_value_current_year], verbose_name='ano')),
                ('Especificacao', models.TextField(blank=True, db_column='especificacao', null=True)),
                ('arquivo_desenho', models.ImageField(blank=True, db_column='arquivo_desenho', null=True, upload_to='media/desenhos_pedidos', verbose_name='Arquivo do desenho')),
                ('desenho', models.CharField(blank=True, db_column='desenho', max_length=150, null=True, verbose_name='Obs. do desenho')),
                ('unidade', models.CharField(blank=True, choices=[('Peça', 'Peça'), ('Jogo', 'Jogo')], db_column='unidade', default='peca', max_length=50, null=True)),
                ('qtd', models.IntegerField(blank=True, db_column='qnt', null=True, verbose_name='Quantidade')),
                ('preco', models.FloatField(blank=True, db_column='preco', null=True, verbose_name='Preço')),
                ('data_entrada', models.DateField(blank=True, db_column='data_entrada', default='02/06/2021', max_length=50, null=True, verbose_name='Data de Entrada')),
                ('qtd_acabada', models.IntegerField(blank=True, db_column='qtd_acabada', null=True, verbose_name='Quantidade Acabada')),
                ('Cliente', models.ForeignKey(db_column='id_cliente', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pedido', to='pepperadmin.cliente')),
                ('item', models.ManyToManyField(blank=True, db_column='id_ferramenta', related_name='item_pedido', to='pepperadmin.Item')),
                ('os_pedido', models.ForeignKey(blank=True, db_column='id_os', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_os', to='pepperadmin.cadastro_os', verbose_name='Ordem de Serviço')),
            ],
        ),
    ]
