# Generated by Django 3.2.3 on 2021-06-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0030_auto_20210602_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='10:32:36', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(blank=True, db_column='descricao', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.ManyToManyField(blank=True, db_column='cod_mat', null=True, related_name='materialitem', to='pepperadmin.Material'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='ano',
            field=models.IntegerField(db_column='ano', default=2021, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='icms',
            field=models.CharField(blank=True, db_column='icms', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='ipi',
            field=models.CharField(blank=True, db_column='ipi', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='item',
            field=models.ManyToManyField(blank=True, db_column='cod_item', null=True, related_name='item_orcamento', to='pepperadmin.Item'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='prazo_entrega',
            field=models.DateTimeField(blank=True, db_column='prazo_entrega', null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='prazo_pagamento',
            field=models.DateTimeField(blank=True, db_column='prazo_pagto', null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ano',
            field=models.IntegerField(db_column='ano', default=2021, verbose_name='ano'),
        ),
    ]
