# Generated by Django 3.2.3 on 2021-06-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0033_auto_20210602_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='numero',
            new_name='numero_pedido',
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='11:24:16', verbose_name='Início'),
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='Pedido',
        ),
    ]
