# Generated by Django 3.2.3 on 2021-06-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0034_auto_20210602_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='12:30:28', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.IntegerField(db_column='numero', editable=False),
        ),
    ]
