# Generated by Django 3.2.3 on 2021-06-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0035_auto_20210602_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='preco',
            new_name='preco_pedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='qtd',
            new_name='qnt',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='unidade',
            new_name='unidade_pedido',
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='12:42:46', verbose_name='Início'),
        ),
    ]
