# Generated by Django 3.2.3 on 2021-06-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0037_auto_20210602_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='14:59:04', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='os_pedido',
            field=models.ForeignKey(blank=True, db_column='id_os', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_os', to='pepperadmin.cadastro_os', verbose_name='Ordem de Serviço'),
        ),
    ]
