# Generated by Django 3.2.3 on 2021-06-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0038_auto_20210602_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='arquivo_desenho',
            field=models.ImageField(blank=True, db_column='arquivo_desenho', null=True, upload_to='media/desenhos_pedidos', verbose_name='Arquivo do desenho'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='15:00:30', verbose_name='Início'),
        ),
    ]
