# Generated by Django 3.2.3 on 2021-06-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0040_auto_20210602_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='pedido_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='pepperadmin.pedido'),
        ),
        migrations.AlterField(
            model_name='cadastro_os',
            name='Data',
            field=models.DateField(blank=True, db_column='Data', default='03/06/2021', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='11:42:16', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2021-06-03', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
    ]
