# Generated by Django 3.2.3 on 2021-06-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0041_auto_20210603_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_os',
            name='Data',
            field=models.DateField(blank=True, db_column='Data', default='07/06/2021', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='22:17:12', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2021-06-06', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
    ]
