# Generated by Django 3.2.3 on 2021-06-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0042_auto_20210606_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qtd',
            field=models.IntegerField(blank=True, db_column='qtd', null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_os',
            name='Data',
            field=models.DateField(blank=True, db_column='Data', default='11/06/2021', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='11:22:35', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2021-06-11', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
    ]
