# Generated by Django 3.2.3 on 2021-06-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0043_auto_20210611_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='11:24:50', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='item',
            name='qtd',
            field=models.IntegerField(blank=True, db_column='qtd', default=1, null=True),
        ),
    ]
