# Generated by Django 3.2.3 on 2021-06-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0045_auto_20210611_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='qnt',
            field=models.IntegerField(blank=True, db_column='qnt', editable=False, null=True, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='total',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='11:55:39', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(blank=True, db_column='descricao', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='qtd',
            field=models.IntegerField(blank=True, db_column='qtd', default=1, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='qnt',
            field=models.IntegerField(blank=True, db_column='qnt', editable=False, null=True, verbose_name='Quantidade'),
        ),
    ]
