# Generated by Django 3.2.3 on 2021-06-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0048_auto_20210611_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='16:00:45', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='cliente_orcamento', to='pepperadmin.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='Cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='cliente_pedido', to='pepperadmin.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='preco_pedido',
            field=models.FloatField(blank=True, db_column='preco', editable=False, null=True, verbose_name='Preço'),
        ),
    ]
