# Generated by Django 3.2.3 on 2021-06-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0049_auto_20210611_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='Tempo_Objetivo',
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='16:10:41', verbose_name='Início'),
        ),
    ]
