# Generated by Django 3.2.3 on 2021-06-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0051_auto_20210614_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='Tempo_Objetivo',
            field=models.TimeField(blank=True, db_column='Tempo_Objetivo', null=True),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='11:38:48', verbose_name='Início'),
        ),
    ]
