# Generated by Django 3.2.3 on 2021-06-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0054_auto_20210614_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='18:41:27', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='prazo_entrega',
            field=models.DateField(blank=True, db_column='prazo_entrega', null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='prazo_pagamento',
            field=models.DateField(blank=True, db_column='prazo_pagto', null=True),
        ),
    ]
