# Generated by Django 3.2.3 on 2021-06-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0055_auto_20210614_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='18:59:23', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='item',
            field=models.ManyToManyField(db_column='cod_item', related_name='item_orcamento', to='pepperadmin.Item'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='item',
            field=models.ManyToManyField(db_column='id_ferramenta', related_name='item_pedido', to='pepperadmin.Item'),
        ),
    ]
