# Generated by Django 3.2.3 on 2021-06-16 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pepperadmin', '0057_auto_20210616_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='15:13:29', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='15:13:29', verbose_name='Início'),
        ),
        migrations.CreateModel(
            name='HistoricalTipo',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=254)),
                ('quantidade', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tipo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMaterial',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=254, null=True)),
                ('custo', models.IntegerField(blank=True, db_column='custo', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical material',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLinha',
            fields=[
                ('nome', models.CharField(db_column='nome', max_length=254)),
                ('numero_inicial', models.IntegerField(db_column='numero_inicial', db_index=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical linha',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFornecedor',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cnpj', localflavor.br.models.BRCNPJField(blank=True, db_column='cnpj', max_length=18, null=True)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=500, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, db_column='telefone', max_length=254, null=True)),
                ('celular', models.CharField(blank=True, db_column='celular', max_length=254, null=True)),
                ('cod_forn', models.CharField(blank=True, db_column='cod_cli', default='', max_length=50, null=True)),
                ('fax', models.CharField(blank=True, db_column='fax', max_length=50, null=True)),
                ('ie', models.CharField(blank=True, db_column='ie', max_length=254, null=True)),
                ('cep', localflavor.br.models.BRPostalCodeField(blank=True, db_column='cep', max_length=9, null=True)),
                ('cidade', models.CharField(blank=True, db_column='cidade', max_length=120, null=True)),
                ('estado', localflavor.br.models.BRStateField(blank=True, db_column='estado', default=None, max_length=2, null=True)),
                ('endereco', models.TextField(blank=True, db_column='endereco', null=True)),
                ('obs', models.CharField(blank=True, db_column='obs', default='', max_length=254, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fornecedor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFerramenta',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=254)),
                ('arquivo_desenho', models.TextField(blank=True, db_column='arquivo_desenho', max_length=100, null=True, verbose_name='Arquivo do desenho')),
                ('relatorio', models.TextField(blank=True, db_column='relatorio', max_length=100, null=True, verbose_name='Relatorio do desenho')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ferramenta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cnpj', localflavor.br.models.BRCNPJField(blank=True, db_column='cnpj', max_length=18, null=True)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=500, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, db_column='telefone', max_length=254, null=True)),
                ('celular', models.CharField(blank=True, db_column='celular', max_length=254, null=True)),
                ('cod_cli', models.CharField(blank=True, db_column='cod_cli', default='', max_length=50, null=True)),
                ('fax', models.CharField(blank=True, db_column='fax', max_length=50, null=True)),
                ('ie', models.CharField(blank=True, db_column='ie', max_length=254, null=True)),
                ('cep', localflavor.br.models.BRPostalCodeField(blank=True, db_column='cep', max_length=9, null=True)),
                ('cidade', models.CharField(blank=True, db_column='cidade', max_length=120, null=True)),
                ('estado', localflavor.br.models.BRStateField(blank=True, db_column='estado', default=None, max_length=2, null=True)),
                ('endereco', models.TextField(blank=True, db_column='endereco', null=True)),
                ('obs', models.CharField(blank=True, db_column='obs', default='', max_length=254, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cliente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
