# Generated by Django 3.2.3 on 2021-06-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0060_auto_20210621_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='16:49:33', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='16:49:33', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='os',
            field=models.ForeignKey(blank=True, db_column='id_os', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_os', to='pepperadmin.cadastro_os', verbose_name='Ordem de Serviço'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='processo',
            field=models.ForeignKey(blank=True, db_column='id_proc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_proc', to='pepperadmin.processo', verbose_name='Processo'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_orcamento', to='pepperadmin.cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='pedido_id',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pepperadmin.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='os_pedido',
            field=models.ForeignKey(blank=True, db_column='id_os', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_os', to='pepperadmin.cadastro_os', verbose_name='Ordem de Serviço'),
        ),
    ]
