# Generated by Django 3.1.12 on 2021-08-09 18:37

from django.db import migrations, models
import django.db.models.deletion
import pepperadmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0061_auto_20210621_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Rosca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='descricao',
            field=models.TextField(blank=True, db_column='descricao', null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='diamrosca',
            field=models.CharField(db_column='diametro_rosca', default='', max_length=254, verbose_name='Diâmetro da Rosca'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='passo',
            field=models.FloatField(blank=True, db_column='passo', default=1, null=True, verbose_name='Passo da Rosca(mm)'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='preco',
            field=models.FloatField(blank=True, db_column='preco', null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='processos',
            field=models.ManyToManyField(related_name='ferramenta_processo', to='pepperadmin.Processo', verbose_name='Processo(s)'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='tempo',
            field=models.FloatField(blank=True, db_column='tempo', null=True, verbose_name='Tempo'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='tolerancia',
            field=models.CharField(db_column='tolerancia', default='', max_length=254, verbose_name='Tolerância'),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='descricao',
            field=models.TextField(blank=True, db_column='descricao', null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='diamrosca',
            field=models.CharField(db_column='diametro_rosca', default='', max_length=254, verbose_name='Diâmetro da Rosca'),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='passo',
            field=models.FloatField(blank=True, db_column='passo', default=1, null=True, verbose_name='Passo da Rosca(mm)'),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='preco',
            field=models.FloatField(blank=True, db_column='preco', null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='tempo',
            field=models.FloatField(blank=True, db_column='tempo', null=True, verbose_name='Tempo'),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='tolerancia',
            field=models.CharField(db_column='tolerancia', default='', max_length=254, verbose_name='Tolerância'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='diamrosca',
            field=models.CharField(db_column='diametro_rosca', default='', max_length=254, verbose_name='Diâmetro da Rosca'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='passo',
            field=models.FloatField(blank=True, db_column='passo', default=1, null=True, verbose_name='Passo da Rosca(mm)'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='rosca',
            field=models.TextField(blank=True, choices=[('canal reto', 'canal reto')], db_column='tipo', default='canal reto', null=True),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='tempo',
            field=models.FloatField(blank=True, db_column='tempo', null=True, verbose_name='Tempo'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='tolerancia',
            field=models.CharField(db_column='tolerancia', default='', max_length=254, verbose_name='Tolerância'),
        ),
        migrations.AddField(
            model_name='item',
            name='diamrosca',
            field=models.CharField(db_column='diametro_rosca', default='', max_length=254, verbose_name='Diâmetro da Rosca'),
        ),
        migrations.AddField(
            model_name='item',
            name='passo',
            field=models.FloatField(blank=True, db_column='passo', default=1, null=True, verbose_name='Passo da Rosca(mm)'),
        ),
        migrations.AddField(
            model_name='item',
            name='processos',
            field=models.ManyToManyField(related_name='item_processo', to='pepperadmin.Processo', verbose_name='Processo(s)'),
        ),
        migrations.AddField(
            model_name='item',
            name='rosca',
            field=models.TextField(blank=True, choices=[('canal reto', 'canal reto')], db_column='tipo', default='canal reto', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tempo',
            field=models.FloatField(blank=True, db_column='tempo', null=True, verbose_name='Tempo'),
        ),
        migrations.AddField(
            model_name='item',
            name='tolerancia',
            field=models.CharField(db_column='tolerancia', default='', max_length=254, verbose_name='Tolerância'),
        ),
        migrations.AlterField(
            model_name='cadastro_os',
            name='Data',
            field=models.DateField(blank=True, db_column='Data', default='2021-08-09', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcadastro_os',
            name='Data',
            field=models.DateField(blank=True, db_column='Data', default='2021-08-09', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='15:37:15', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2021-08-09', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='numero_pedido',
            field=models.IntegerField(db_column='numero', default=pepperadmin.models.Pedido.get_last_pedido, editable=False),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='15:37:15', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='item',
            field=models.ManyToManyField(db_column='cod_ferramenta', related_name='item_orcamento', to='pepperadmin.Ferramenta'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2021-08-09', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='item',
            field=models.ManyToManyField(db_column='id_ferramenta', related_name='item_pedido', to='pepperadmin.Ferramenta'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.IntegerField(db_column='numero', default=pepperadmin.models.Pedido.get_last_pedido, editable=False),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='norma',
            field=models.ForeignKey(db_column='formato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferramenta_formato', to='pepperadmin.formato'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='rosca',
            field=models.ForeignKey(db_column='tipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferramenta_rosca', to='pepperadmin.rosca'),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='norma',
            field=models.ForeignKey(blank=True, db_column='formato', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pepperadmin.formato'),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='rosca',
            field=models.ForeignKey(blank=True, db_column='tipo', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pepperadmin.rosca'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='norma',
            field=models.ForeignKey(blank=True, db_column='formato', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pepperadmin.formato'),
        ),
        migrations.AddField(
            model_name='item',
            name='norma',
            field=models.ForeignKey(db_column='formato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format', to='pepperadmin.formato'),
        ),
    ]
