# Generated by Django 3.1.12 on 2021-08-09 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0062_auto_20210809_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='norma',
            field=models.ForeignKey(db_column='formato', default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferramenta_formato', to='pepperadmin.formato'),
        ),
        migrations.AlterField(
            model_name='historicalferramenta',
            name='norma',
            field=models.ForeignKey(blank=True, db_column='formato', db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pepperadmin.formato'),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='18:07:39', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='18:07:39', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='item',
            field=models.ManyToManyField(db_column='cod_ferramenta', related_name='item_orcamento', to='pepperadmin.Ferramenta', verbose_name='Ferramenta(s)'),
        ),
    ]
