# Generated by Django 3.1.12 on 2021-08-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0064_auto_20210830_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='qtd',
            field=models.IntegerField(blank=True, db_column='qtd', default=1, null=True, verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='qtd',
            field=models.IntegerField(blank=True, db_column='qtd', default=1, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='14:49:49', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='14:49:49', verbose_name='Início'),
        ),
    ]
