# Generated by Django 3.1.12 on 2021-08-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0065_auto_20210830_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='preco',
            field=models.FloatField(blank=True, db_column='preco', null=True, verbose_name='Preço por unidade'),
        ),
        migrations.AlterField(
            model_name='historicalferramenta',
            name='preco',
            field=models.FloatField(blank=True, db_column='preco', null=True, verbose_name='Preço por unidade'),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='14:56:53', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='14:56:53', verbose_name='Início'),
        ),
    ]
