# Generated by Django 3.1.12 on 2021-08-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0066_auto_20210830_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='diamnuceo',
            field=models.FloatField(blank=True, db_column='diametro_nucleo', null=True, verbose_name='Diâmetro do Núcleo'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='diamtotal',
            field=models.FloatField(blank=True, db_column='diametro_total', null=True, verbose_name='Diâmetro Total '),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='diamnuceo',
            field=models.FloatField(blank=True, db_column='diametro_nucleo', null=True, verbose_name='Diâmetro do Núcleo'),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='diamtotal',
            field=models.FloatField(blank=True, db_column='diametro_total', null=True, verbose_name='Diâmetro Total '),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='15:32:52', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='15:32:52', verbose_name='Início'),
        ),
    ]
