# Generated by Django 3.1.3 on 2021-10-04 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pepperadmin', '0067_auto_20210830_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhistorico_os',
            name='id_func',
            field=models.ForeignKey(blank=True, db_column='Colaborador', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historico_os',
            name='id_func',
            field=models.ForeignKey(blank=True, db_column='Colaborador', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cadastro_os',
            name='Data',
            field=models.DateField(blank=True, db_column='Data', default='2021-10-04', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcadastro_os',
            name='Data',
            field=models.DateField(blank=True, db_column='Data', default='2021-10-04', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='18:08:16', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2021-10-04', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='18:08:16', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2021-10-04', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
    ]
