# Generated by Django 3.1.3 on 2022-01-03 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0069_auto_20211210_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico_os',
            options={'ordering': ['-fim'], 'verbose_name': 'Localização O.S', 'verbose_name_plural': 'Localizar O.S'},
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='diamnuceo',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='diamrosca',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='diamtotal',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='norma',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='passo',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='qtd',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='rosca',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='tolerancia',
        ),
        migrations.RemoveField(
            model_name='historicalferramenta',
            name='diamnuceo',
        ),
        migrations.RemoveField(
            model_name='historicalferramenta',
            name='diamrosca',
        ),
        migrations.RemoveField(
            model_name='historicalferramenta',
            name='diamtotal',
        ),
        migrations.RemoveField(
            model_name='historicalferramenta',
            name='norma',
        ),
        migrations.RemoveField(
            model_name='historicalferramenta',
            name='passo',
        ),
        migrations.RemoveField(
            model_name='historicalferramenta',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='historicalferramenta',
            name='qtd',
        ),
        migrations.RemoveField(
            model_name='historicalferramenta',
            name='rosca',
        ),
        migrations.RemoveField(
            model_name='historicalferramenta',
            name='tolerancia',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='diamrosca',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='norma',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='passo',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='qtd',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='rosca',
        ),
        migrations.RemoveField(
            model_name='historicalitem',
            name='tolerancia',
        ),
        migrations.RemoveField(
            model_name='item',
            name='diamrosca',
        ),
        migrations.RemoveField(
            model_name='item',
            name='norma',
        ),
        migrations.RemoveField(
            model_name='item',
            name='passo',
        ),
        migrations.RemoveField(
            model_name='item',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='item',
            name='qtd',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rosca',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tolerancia',
        ),
        migrations.AlterField(
            model_name='cadastro_os',
            name='Data',
            field=models.DateField(blank=True, db_column='Data', default=datetime.date.today, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcadastro_os',
            name='Data',
            field=models.DateField(blank=True, db_column='Data', default=datetime.date.today, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='inicio',
            field=models.TimeField(blank=True, db_column='inicio', editable=False, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='historicalorcamento',
            name='ano',
            field=models.IntegerField(db_column='ano', default=2022, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='ano',
            field=models.IntegerField(db_column='ano', default=2022, editable=False, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2022-01-03', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(auto_now_add=True, db_column='inicio', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='ano',
            field=models.IntegerField(db_column='ano', default=2022, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ano',
            field=models.IntegerField(db_column='ano', default=2022, editable=False, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2022-01-03', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
    ]
