# Generated by Django 3.1.3 on 2021-11-02 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pepperadmin', '0069_auto_20211020_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_os',
            name='Data',
            field=models.DateField(blank=True, db_column='Data', default='2021-11-02', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_os',
            name='Linha',
            field=models.ForeignKey(blank=True, db_column='id_Linha', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linha_os', to='pepperadmin.linha', verbose_name='Linha de Produção'),
        ),
        migrations.AlterField(
            model_name='cadastro_os',
            name='Quantidade',
            field=models.IntegerField(blank=True, db_column='Quantidade', null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='historicalcadastro_os',
            name='Data',
            field=models.DateField(blank=True, db_column='Data', default='2021-11-02', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcadastro_os',
            name='Linha',
            field=models.ForeignKey(blank=True, db_column='id_Linha', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pepperadmin.linha', verbose_name='Linha de Produção'),
        ),
        migrations.AlterField(
            model_name='historicalcadastro_os',
            name='Quantidade',
            field=models.IntegerField(blank=True, db_column='Quantidade', null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='id_func',
            field=models.ForeignKey(blank=True, db_column='Colaborador', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador que iniciou'),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='id_func_fim',
            field=models.ForeignKey(blank=True, db_column='Colaborador_Final', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador que finalizou'),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='23:18:37', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='ocorrencias',
            field=models.TextField(blank=True, db_column='ocorrencias', null=True, verbose_name='Ocorrência(s)'),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='periodo',
            field=models.IntegerField(blank=True, db_column='periodo', null=True, verbose_name='Período(s)'),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='qtd',
            field=models.IntegerField(blank=True, db_column='qtd', null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2021-11-01', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='id_func',
            field=models.ForeignKey(blank=True, db_column='Colaborador', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Colaborador que iniciou'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='id_func_fim',
            field=models.ForeignKey(blank=True, db_column='Colaborador_Final', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_func_fim', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador que finalizou'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='inicio',
            field=models.TimeField(db_column='inicio', default='23:18:37', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='ocorrencias',
            field=models.TextField(blank=True, db_column='ocorrencias', null=True, verbose_name='Ocorrência(s)'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='periodo',
            field=models.IntegerField(blank=True, db_column='periodo', null=True, verbose_name='Período(s)'),
        ),
        migrations.AlterField(
            model_name='historico_os',
            name='qtd',
            field=models.IntegerField(blank=True, db_column='qtd', null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='item',
            name='arquivo_desenho',
            field=models.FileField(blank=True, db_column='arquivo_desenho', null=True, upload_to='media/', verbose_name='Arquivo do desenho'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2021-11-01', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
    ]
