# Generated by Django 5.0.6 on 2024-06-27 12:20

import pepperadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0070_auto_20220103_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='ferramenta',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='formato',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='historicalcadastro_os',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Ordem de Serviço', 'verbose_name_plural': 'historical Ordem de Serviços'},
        ),
        migrations.AlterModelOptions(
            name='historicalcliente',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical cliente', 'verbose_name_plural': 'historical clientes'},
        ),
        migrations.AlterModelOptions(
            name='historicalferramenta',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ferramenta', 'verbose_name_plural': 'historical ferramentas'},
        ),
        migrations.AlterModelOptions(
            name='historicalfornecedor',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical fornecedor', 'verbose_name_plural': 'historical fornecedors'},
        ),
        migrations.AlterModelOptions(
            name='historicalhistorico_os',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Localização O.S', 'verbose_name_plural': 'historical Localizar O.S'},
        ),
        migrations.AlterModelOptions(
            name='historicalitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical item', 'verbose_name_plural': 'historical Itens'},
        ),
        migrations.AlterModelOptions(
            name='historicallinha',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical linha', 'verbose_name_plural': 'historical linhas'},
        ),
        migrations.AlterModelOptions(
            name='historicalmaterial',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical material', 'verbose_name_plural': 'historical Materiais'},
        ),
        migrations.AlterModelOptions(
            name='historicalorcamento',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Orçamento', 'verbose_name_plural': 'historical Orçamentos'},
        ),
        migrations.AlterModelOptions(
            name='historicalpedido',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical pedido', 'verbose_name_plural': 'historical pedidos'},
        ),
        migrations.AlterModelOptions(
            name='historicalprocesso',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical processo', 'verbose_name_plural': 'historical processos'},
        ),
        migrations.AlterModelOptions(
            name='historicaltipo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tipo', 'verbose_name_plural': 'historical tipos'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='linha',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Materiais'},
        ),
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['procname']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='rosca',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='codigo_do_cliente',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='codigo_do_cliente',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalcadastro_os',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalferramenta',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfornecedor',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalhistorico_os',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallinha',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalorcamento',
            name='ano',
            field=models.IntegerField(db_column='ano', default=2024, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='historicalorcamento',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='ano',
            field=models.IntegerField(db_column='ano', default=2024, editable=False, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2024-06-27', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='numero_pedido',
            field=models.IntegerField(db_column='numero', default=pepperadmin.models.get_last_pedido_out, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalprocesso',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltipo',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='ano',
            field=models.IntegerField(db_column='ano', default=2024, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ano',
            field=models.IntegerField(db_column='ano', default=2024, editable=False, verbose_name='ano'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2024-06-27', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.IntegerField(db_column='numero', default=pepperadmin.models.get_last_pedido_out, editable=False),
        ),
    ]
