# Generated by Django 5.0.6 on 2024-06-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0071_alter_cliente_options_alter_ferramenta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='codigo_do_desenho_da_pimentel',
            field=models.CharField(default='', max_length=254, verbose_name='Codigo do desenho da Pimentel'),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='codigo_do_desenho_da_pimentel',
            field=models.CharField(default='', max_length=254, verbose_name='Codigo do desenho da Pimentel'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='codigo_do_cliente',
            field=models.CharField(default='', max_length=254, verbose_name='Codigo do item que está na N.F'),
        ),
        migrations.AlterField(
            model_name='historicalferramenta',
            name='codigo_do_cliente',
            field=models.CharField(default='', max_length=254, verbose_name='Codigo do item que está na N.F'),
        ),
    ]
