# Generated by Django 5.1.2 on 2024-10-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperadmin', '0072_ferramenta_codigo_do_desenho_da_pimentel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_os',
            name='nota_fiscal_cobranca',
            field=models.IntegerField(blank=True, db_column='nota_fiscal_cobranca', null=True),
        ),
        migrations.AddField(
            model_name='cadastro_os',
            name='nota_fiscal_retorno',
            field=models.IntegerField(blank=True, db_column='nota_fiscal_retorno', null=True),
        ),
        migrations.AddField(
            model_name='cadastro_os',
            name='peso',
            field=models.FloatField(blank=True, db_column='peso', null=True),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='peso',
            field=models.IntegerField(blank=True, db_column='peso', null=True),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='preco',
            field=models.FloatField(blank=True, db_column='preco', null=True, verbose_name='Preço por unidade'),
        ),
        migrations.AddField(
            model_name='historicalcadastro_os',
            name='nota_fiscal_cobranca',
            field=models.IntegerField(blank=True, db_column='nota_fiscal_cobranca', null=True),
        ),
        migrations.AddField(
            model_name='historicalcadastro_os',
            name='nota_fiscal_retorno',
            field=models.IntegerField(blank=True, db_column='nota_fiscal_retorno', null=True),
        ),
        migrations.AddField(
            model_name='historicalcadastro_os',
            name='peso',
            field=models.FloatField(blank=True, db_column='peso', null=True),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='peso',
            field=models.IntegerField(blank=True, db_column='peso', null=True),
        ),
        migrations.AddField(
            model_name='historicalferramenta',
            name='preco',
            field=models.FloatField(blank=True, db_column='preco', null=True, verbose_name='Preço por unidade'),
        ),
        migrations.AddField(
            model_name='historicalpedido',
            name='Numero_Nf',
            field=models.IntegerField(blank=True, db_column='Numero_Nf', null=True),
        ),
        migrations.AddField(
            model_name='historicalpedido',
            name='nota_fiscal_cobranca',
            field=models.IntegerField(blank=True, db_column='nota_fiscal_cobranca', null=True),
        ),
        migrations.AddField(
            model_name='historicalpedido',
            name='nota_fiscal_retorno',
            field=models.IntegerField(blank=True, db_column='nota_fiscal_retorno', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='Numero_Nf',
            field=models.IntegerField(blank=True, db_column='Numero_Nf', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nota_fiscal_cobranca',
            field=models.IntegerField(blank=True, db_column='nota_fiscal_cobranca', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nota_fiscal_retorno',
            field=models.IntegerField(blank=True, db_column='nota_fiscal_retorno', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaterial',
            name='nome',
            field=models.CharField(db_column='nome', default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2024-10-24', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nome',
            field=models.CharField(db_column='nome', default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrada',
            field=models.DateField(blank=True, db_column='data_entrada', default='2024-10-24', max_length=50, null=True, verbose_name='Data de Entrada'),
        ),
    ]
